Test introduction check

diff --git a/.github/workflows/lint-changelog.yaml b/.github/workflows/lint-changelog.yaml
--- a/.github/workflows/lint-changelog.yaml
+++ b/.github/workflows/lint-changelog.yaml
@@ -16,6 +16,18 @@ jobs:
     - name: Install dependencies
       run: |
         pip install parse-changelog
-        sudo apt-get install --yes jq
-    - name: Parse changelog
-      run: parse-changelog --changelog ./CHANGELOG.md
+    - name: Parse changelog to JSON
+      run: |
+        parse-changelog --changelog ./CHANGELOG.md > _changelog.json
+    - name: Print parsed changelog
+      run: |
+        jq . _changelog.json
+    - name: Check if introduction is present
+      run: |
+        jq -e 'has("introduction")') || (echo "::error file=CHANGELOG.md,line=1,col=1::Missing introduction" && exit 1)
+    - name: Check if introduction title is present
+      run: |
+        jq -e '.introduction | has("title")') || (echo "::error file=CHANGELOG.md,line=1,col=1::Missing introduction title" && exit 1)
+    - name: Check if introduction content is present
+      run: |
+        jq -e '.introduction | has("content")') || (echo "::error file=CHANGELOG.md,line=1,col=1::Missing introduction content" && exit 1)
